name: Make a Bookmark in Raindrop.io from TechCrunch RSS
on:
  rss:
    url: https://techcrunch.com/feed/
jobs:
  request:
    name: Request
    runs-on: ubuntu-latest
    steps:
      - name: Send Bookmark to Raindrop.io      
        uses: actionsflow/axios@main
        with:
          url: https://api.raindrop.io/rest/v1/raindrop
          bearer-token: ${{ secrets.BEARER_TOKEN }}
          headers: '{ "Content-Type": "application/json; charset=utf-8" }'
          method: POST
          data: '{ "link":"${{on.rss.outputs.link}}", "title": "${{on.rss.outputs.title}}", "collection": { "$id": "14422740" }, "pleaseParse": {} }'
           
  webhook:
    name: Send HTTP Request to Slack Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP Request
        uses: actionsflow/axios@v1
        with:
          url: ${{ secrets.WALT_NEWS_WEBHOOK }}
          method: 'POST'
          body: '{ "text": "*<${{on.rss.outputs.link}}| ${{on.rss.outputs.title}}>*", "unfurl_media":true, "unfurl_links":true }'
