name: Make a Bookmark in Raindrop.io from Github Tredning RSS and Send it to Slack
on:
  rss:
    url: https://mshibanami.github.io/GitHubTrendingRSS/daily/all.xml
    
jobs:
  request:
    name: Request
    runs-on: ubuntu-latest
    steps:
      - name: Send Bookmark to Raindrop.io      
        uses: actionsflow/axios@main
        with:
          url: https://f09c0d583cdd2b4aa0e22f94b7cabd5f.m.pipedream.net
          bearer-token: ${{ secrets.BEARER_TOKEN }}
          headers: '{ "Content-Type": "application/json; charset=utf-8" }'
          method: POST
          data: '{ "link":"${{on.rss.outputs.link}}", "collection": { "$id": "14423153" }, "pleaseParse": {} }'
 
  webhook:
    name: Send HTTP Request to Slack Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP Request
        uses: actionsflow/axios@v1
        with:
          url: https://f09c0d583cdd2b4aa0e22f94b7cabd5f.m.pipedream.net
          method: 'POST'
          body: '{ "text": "*<${{on.rss.outputs.link}}| ${{on.rss.outputs.title}}>*", "unfurl_media":true, "unfurl_links":true }'
