name: Make a Bookmark in Raindrop.io from Vox RSS
on:
  rss:
    url: https://www.vox.com/rss/index.xml
jobs:
  request:
    name: Request
    runs-on: ubuntu-latest
    steps:
      - name: Send Bookmark to Raindrop.io      
        uses: actionsflow/axios@main
        with:
          url: https://api.raindrop.io/rest/v1/raindrop
          bearer-token: ${{ secrets.bearer_token }}
          content-type: application/json
          method: POST
          data: |
            {
              "link":"${{on.rss.outputs.link}}", 
              "title": "${{on.rss.outputs.title}}",
              "collection": {
              "$id": "14422740"
              }
              "pleaseParse": {}
            }
