name: Send Ask4Movie RSS to Slack
on:
  rss:
    url: ttp://ask4movie.co/feed/
    
jobs:
  webhook:
    name: Send HTTP Request to Slack Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP Request
        uses: actionsflow/axios@v1
        with:
          url: ${{ secrets.WALT_TORRENT_WEBHOOK }}
          method: 'POST'
          body: '{ "text": "*<${{on.rss.outputs.link}}| ${{on.rss.outputs.title}}>*", "unfurl_media":true, "unfurl_links":true }'