name: Send Youtube Video to Slack
on:
  youtube:
    channel_id:
      - UCddiUEpeqJcYeBxX1IVBKvQ
      - UCE_M8A5yxnLfW0KghEeajjw
      - UCUHW94eEFW7hkUMVaZz4eDg
      - UCtxJFU9DgUhfr2J2bveCHkQ
      - UCrM7B7SL_g1edFOnmj-SDKg
      - UCUMZ7gohGI9HcU9VNsr2FJQ
      - UC9uD-W5zQHQuAVT2GdcLCvg
      - UCzWQYUVCpZqtN93H8RR44Qw
      - UCLXo7UDZvByw2ixzpQCufnA
      - UCRXRbi80k0_vcIfgpOSerTg
      - UCfzOLBT7jyHFcaTgwmnttog
      - UCsBjURrPoezykLs9EqgamOA
      - UC8butISFwT-Wl7EV0hUK0BQ
      - UC1_uAIS3r8Vu6JjXWvastJg
      - UCHnj59g7jezwTy5GeL8EA_g
      - UCYO_jab_esuFRV4b17AJtAw
      - UC1ZBQ-F-yktYD4m5AzM6pww
jobs:
  webhook:
    name: Send HTTP Request
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP Request
        uses: actionsflow/axios@v1
        with:
          url: https://hooks.slack.com/services/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
          method: 'POST'
          body: '{ "text": "*<${{on.youtube.outputs.link}}| ${{on.youtube.outputs.title}}>*", "unfurl_media":true, "unfurl_links":true }'
