name: Send a HTTP Request when new RSS item is detected
on:
  rss:
    url: https://vox.com/rss/index.xml
jobs:
  request:
    name: Request
    runs-on: ubuntu-latest
    steps:
      - name: Make a HTTP Request      
        uses: actionsflow/axios@main
        with:
          url: https://hookb.in/BYzWD7eQ9jsLDDx31Koq
          method: POST
          body: |
            {
              "link":"${{on.rss.outputs.link}}", 
              "title": "${{on.rss.outputs.title}}",
              "content":"<<<${{on.rss.outputs.contentSnippet}}>>>"
            }
